/**
 * @OnlyCurrentDoc
 *
 * Google Apps Script - Manifest-only Resource Link Updater
 *
 * Use this file when you want the lowest-scope Apps Script flow.
 * It does not use Drive services, folder scanning, saved properties, or cross-deck merge helpers.
 *
 * Setup:
 * 1. Generate a resource manifest locally:
 *    node scripts/google_slides_resource_cli.js manifest --pdf-folder "<Drive folder URL>" --manifest-out resources-manifest.json
 * 2. Open the Google Slides deck.
 * 3. Extensions > Apps Script.
 * 4. Paste this whole file into Code.gs.
 * 5. Replace appsscript.json with IMPORTANT/GOOGLE_SLIDES_RESOURCE_LOW_SCOPE_appsscript.json.
 * 6. Reload the Slides deck.
 * 7. Resource Tools > Link Resources from Manifest.
 */

function onOpen() {
  SlidesApp.getUi()
    .createMenu("Resource Tools")
    .addItem("Link Resources from Manifest", "showLinkResourcesFromManifestDialog")
    .addToUi();
}

function showLinkResourcesFromManifestDialog() {
  var html = HtmlService.createHtmlOutput(
    '<div style="font-family:Arial,sans-serif;padding:14px;">' +
      '<h2 style="font-size:16px;margin:0 0 8px;">Link Resources from Manifest</h2>' +
      '<p style="font-size:13px;line-height:1.4;margin:0 0 10px;">Paste the JSON manifest generated by the local runner.</p>' +
      '<input id="manifestFile" type="file" accept=".json,application/json" onchange="loadManifestFile()" style="box-sizing:border-box;width:100%;margin:0 0 8px;" />' +
      '<textarea id="manifest" style="box-sizing:border-box;width:100%;height:260px;font-family:monospace;font-size:12px;"></textarea>' +
      '<div id="status" style="font-size:12px;color:#555;margin-top:8px;"></div>' +
      '<div style="margin-top:12px;text-align:right;">' +
        '<button onclick="google.script.host.close()" style="margin-right:8px;">Cancel</button>' +
        '<button onclick="runLink()">Link resources</button>' +
      '</div>' +
      '<script>' +
        'function loadManifestFile(){' +
          'var input=document.getElementById("manifestFile");' +
          'var file=input.files && input.files[0];' +
          'if(!file)return;' +
          'var status=document.getElementById("status");' +
          'var reader=new FileReader();' +
          'reader.onload=function(){document.getElementById("manifest").value=String(reader.result||"");status.textContent="Loaded "+file.name;};' +
          'reader.onerror=function(){status.textContent="Could not read "+file.name;};' +
          'reader.readAsText(file);' +
        '}' +
        'function runLink(){' +
          'var status=document.getElementById("status");' +
          'status.textContent="Linking resources...";' +
          'google.script.run' +
            '.withSuccessHandler(function(){status.textContent="Done. You can close this dialog.";})' +
            '.withFailureHandler(function(e){status.textContent=e && e.message ? e.message : String(e);})' +
            '.linkResourcesFromManifestText(document.getElementById("manifest").value);' +
        '}' +
      '</script>' +
    '</div>'
  )
    .setWidth(620)
    .setHeight(430);

  SlidesApp.getUi().showModalDialog(html, "Link Resources from Manifest");
}

function linkResourcesFromManifestText(manifestText) {
  var pdfMap = buildPdfMapFromManifest_(manifestText);
  var pdfCount = uniquePdfCount_(pdfMap);

  if (pdfCount === 0) {
    throw new Error("The manifest did not contain any PDF resource links.");
  }

  return linkResourcesFromPdfMap_(pdfMap, pdfCount);
}

function buildPdfMapFromManifest_(manifestText) {
  var raw = parseManifestJson_(manifestText);

  var entries = [];

  if (Array.isArray(raw)) {
    entries = raw;
  } else if (raw && Array.isArray(raw.resources)) {
    entries = raw.resources;
  } else if (raw && Array.isArray(raw.files)) {
    entries = raw.files;
  } else if (raw && typeof raw === "object") {
    var keys = Object.keys(raw);
    for (var i = 0; i < keys.length; i++) {
      var value = raw[keys[i]];
      if (value && typeof value === "object") {
        entries.push({
          name: value.name || value.filename || value.fileName || keys[i],
          url: value.url || value.webViewLink || value.link || value.driveUrl || value.webUrl || ""
        });
      } else {
        entries.push({ name: keys[i], url: value });
      }
    }
  } else {
    throw new Error("Manifest must be a JSON array, an object with resources/files, or a filename-to-URL object.");
  }

  var map = {};

  for (var e = 0; e < entries.length; e++) {
    var entry = entries[e];
    if (!entry) continue;

    var name = String(entry.name || entry.filename || entry.fileName || entry.title || "").trim();
    var url = String(entry.url || entry.webViewLink || entry.link || entry.driveUrl || entry.webUrl || "").trim();

    if (!name || !url) continue;

    var stem = stripExtension(name);
    var normalizedStem = normalizeName(stem);
    var mapped = { name: name, url: url, stem: stem };

    map[normalizedStem] = mapped;
    if (normalizedStem !== stem) {
      map[stem] = mapped;
    }
  }

  return map;
}

function parseManifestJson_(manifestText) {
  var text = String(manifestText || "").replace(/^\uFEFF/, "").trim();

  if (!text) {
    throw new Error("Manifest text is empty. Open resources-manifest.json and paste the file contents.");
  }

  text = stripMarkdownFence_(text);

  try {
    return JSON.parse(text);
  } catch (firstError) {
    var embedded = parseEmbeddedJson_(text);
    if (embedded !== null) {
      return embedded;
    }
  }

  if (/Resource manifest written to/i.test(text)) {
    throw new Error("That is the CLI status line, not the JSON manifest. Open the resources-manifest.json file it names and paste the file contents.");
  }

  throw new Error("Could not parse JSON. Paste the contents of resources-manifest.json, starting with { or [, not the command output line.");
}

function stripMarkdownFence_(text) {
  var fullFence = text.match(/^```(?:json|javascript|js)?\s*([\s\S]*?)\s*```$/i);
  if (fullFence) return fullFence[1].trim();

  var embeddedFence = text.match(/```(?:json|javascript|js)?\s*([\s\S]*?)```/i);
  if (embeddedFence) return embeddedFence[1].trim();

  return text;
}

function parseEmbeddedJson_(text) {
  for (var i = 0; i < text.length; i++) {
    var openChar = text.charAt(i);
    if (openChar !== "{" && openChar !== "[") continue;

    var closeChar = openChar === "{" ? "}" : "]";
    var endIndex = findMatchingJsonEnd_(text, i, openChar, closeChar);
    if (endIndex === -1) continue;

    var candidate = text.substring(i, endIndex + 1).trim();
    try {
      return JSON.parse(candidate);
    } catch (e) {
      // Keep scanning in case the pasted text contains non-JSON brackets before the manifest.
    }
  }

  return null;
}

function findMatchingJsonEnd_(text, startIndex, openChar, closeChar) {
  var depth = 0;
  var inString = false;
  var escaped = false;

  for (var i = startIndex; i < text.length; i++) {
    var ch = text.charAt(i);

    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (ch === "\\") {
        escaped = true;
      } else if (ch === "\"") {
        inString = false;
      }
      continue;
    }

    if (ch === "\"") {
      inString = true;
      continue;
    }

    if (ch === openChar) {
      depth++;
    } else if (ch === closeChar) {
      depth--;
      if (depth === 0) return i;
    }
  }

  return -1;
}

function linkResourcesFromPdfMap_(pdfMap, pdfCount) {
  var presentation = SlidesApp.getActivePresentation();
  var slides = presentation.getSlides();
  var updatedCount = 0;
  var matchLog = [];

  for (var s = 0; s < slides.length; s++) {
    var slide = slides[s];
    var elements = slide.getPageElements();

    for (var e = 0; e < elements.length; e++) {
      var element = elements[e];

      if (element.getPageElementType() === SlidesApp.PageElementType.SHAPE) {
        updatedCount += linkShapeRuns_(element.asShape(), s, pdfMap, matchLog);
      }

      if (element.getPageElementType() === SlidesApp.PageElementType.TABLE) {
        updatedCount += linkTableRuns_(element.asTable(), s, pdfMap, matchLog);
      }
    }
  }

  var report = "Resource Link Update Complete\n\n";
  report += "PDFs found in manifest: " + pdfCount + "\n";
  report += "Links updated: " + updatedCount + "\n\n";

  if (matchLog.length > 0) {
    report += "Matches:\n";
    for (var m = 0; m < matchLog.length; m++) {
      report += "  " + matchLog[m] + "\n";
    }
  }

  if (updatedCount === 0) {
    report += "\nNo matches found. Check that resource slide text matches PDF filenames.\n";
  }

  SlidesApp.getUi().alert("Results", report, SlidesApp.getUi().ButtonSet.OK);
  return { pdfCount: pdfCount, updatedCount: updatedCount, matches: matchLog };
}

function linkShapeRuns_(shape, slideIndex, pdfMap, matchLog) {
  if (!shape.getText) return 0;
  return linkTextRuns_(shape.getText().getRuns(), slideIndex, pdfMap, matchLog, "shape");
}

function linkTableRuns_(table, slideIndex, pdfMap, matchLog) {
  var updatedCount = 0;

  for (var row = 0; row < table.getNumRows(); row++) {
    for (var col = 0; col < table.getNumColumns(); col++) {
      var cell = table.getCell(row, col);
      updatedCount += linkTextRuns_(cell.getText().getRuns(), slideIndex, pdfMap, matchLog, "table");
    }
  }

  return updatedCount;
}

function linkTextRuns_(runs, slideIndex, pdfMap, matchLog, location) {
  var updatedCount = 0;

  for (var r = 0; r < runs.length; r++) {
    var run = runs[r];
    var runText = run.asString().trim();
    var link = run.getTextStyle().getLink();

    var matched = findBestMatch(runText, pdfMap);
    if (!matched && link) {
      matched = findLocalPathMatch_(link, pdfMap);
    }

    if (!matched) continue;

    run.getTextStyle().setLinkUrl(matched.url);
    updatedCount++;
    matchLog.push("Slide " + (slideIndex + 1) + " (" + location + "): \"" + truncate(runText, 40) + "\" -> " + matched.name);
  }

  return updatedCount;
}

function findLocalPathMatch_(link, pdfMap) {
  var linkUrl = "";
  try {
    linkUrl = link.getUrl() || "";
  } catch (e) {
    return null;
  }

  if (!linkUrl || !isLocalPath(linkUrl)) {
    return null;
  }

  var localFilename = extractFilenameFromPath(linkUrl);
  var localStem = stripExtension(localFilename);
  return pdfMap[localStem] || pdfMap[normalizeName(localStem)] || null;
}

function findBestMatch(text, pdfMap) {
  if (!text || text.length < 3) return null;

  var normalizedText = normalizeName(text);
  var minPartialMatchLength = 8;

  if (pdfMap[normalizedText]) return pdfMap[normalizedText];

  var keys = Object.keys(pdfMap);
  var bestMatch = null;
  var bestLength = 0;

  for (var i = 0; i < keys.length; i++) {
    var key = keys[i];
    var normalizedKey = normalizeName(key);

    if (normalizedKey.length >= minPartialMatchLength && normalizedText.indexOf(normalizedKey) !== -1) {
      if (normalizedKey.length > bestLength) {
        bestMatch = pdfMap[key];
        bestLength = normalizedKey.length;
      }
    }
  }

  return bestMatch;
}

function uniquePdfCount_(pdfMap) {
  var seen = {};
  var keys = Object.keys(pdfMap || {});

  for (var i = 0; i < keys.length; i++) {
    var entry = pdfMap[keys[i]];
    if (!entry || !entry.url) continue;
    seen[entry.url] = true;
  }

  return Object.keys(seen).length;
}

function normalizeName(name) {
  return String(name || "")
    .toLowerCase()
    .replace(/[_-]+/g, " ")
    .replace(/\.pdf$/i, "")
    .replace(/\s+/g, " ")
    .trim();
}

function stripExtension(filename) {
  return String(filename || "").replace(/\.[^.]+$/, "");
}

function isLocalPath(url) {
  if (!url) return false;
  return !/^https?:\/\//.test(url) || url.indexOf("file://") === 0;
}

function extractFilenameFromPath(pathValue) {
  if (!pathValue) return "";
  var parts = String(pathValue).replace(/\\/g, "/").split("/");
  return parts[parts.length - 1] || "";
}

function truncate(str, maxLen) {
  if (!str) return "";
  if (str.length <= maxLen) return str;
  return str.substring(0, maxLen - 3) + "...";
}
